- hosts: monitor
  become: true
  tasks:
    - name: Install Prometheus
      shell: |
        cd /opt
        wget https://github.com/prometheus/prometheus/releases/download/v2.26.0/prometheus-2.26.0.linux-amd64.tar.gz
        tar -xzf prometheus-2.26.0.linux-amd64.tar.gz
        cd prometheus-2.26.0.linux-amd64
        ./prometheus --config.file=prometheus.yml &

    - name: Install Grafana
      shell: |
        sudo apt-get install -y adduser libfontconfig1
        wget https://dl.grafana.com/oss/release/grafana_8.5.2_amd64.deb
        sudo dpkg -i grafana_8.5.2_amd64.deb
        sudo systemctl start grafana-server
        sudo systemctl enable grafana-server
